apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-1
  labels:
    app: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: prioridade
            operator: In
            values:
            - "1"
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "512Mi"
        cpu: "0.5"

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "512Mi"
        cpu: "0.5"

---

apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-3
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx
    resources:
      limits:
        memory: "512Mi"
        cpu: "0.5"